In [1]:
import numpy as np

In [ ]:
#Q3: Create a 4×5 numpy array of all True’s.

In [4]:
q3=np.array([['True','True','True','True','True'],
             ['True','True','True','True','True'],
             ['True','True','True','True','True'],
             ['True','True','True','True','True']])
q3

array([['True', 'True', 'True', 'True', 'True'],
       ['True', 'True', 'True', 'True', 'True'],
       ['True', 'True', 'True', 'True', 'True'],
       ['True', 'True', 'True', 'True', 'True']], dtype='<U4')

In [ ]:
#Q4: Create an array of integers from 10 to 50 with with step of 3. Save the array in a. Replace all even numbers in a with -1.

In [6]:
a=np.arange(10,50,3)
a

array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49])

In [7]:
a[a%2==0]=-1
a

array([-1, 13, -1, 19, -1, 25, -1, 31, -1, 37, -1, 43, -1, 49])

In [ ]:
# Q5: Create an one-dimensional array which includes odd numbers from 1 to 20.

In [8]:
q5=np.arange(1,20,2)
q5

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [9]:
#a: Change all numbers divisible by 3 into 0.
q5[q5%3==0]=0
q5

array([ 1,  0,  5,  7,  0, 11, 13,  0, 17, 19])

In [ ]:
# b: Change the array into a 2x5 matrix.

In [11]:
q5=q5.reshape(2,5)
q5

array([[ 1,  0,  5,  7,  0],
       [11, 13,  0, 17, 19]])

In [ ]:
# c: Convert all numbers of the third column into zero.

In [12]:
q5[:,3]=0
q5

array([[ 1,  0,  5,  0,  0],
       [11, 13,  0,  0, 19]])

In [ ]:
#Q6:
#a: Create an one-dimensional array, b1, which includes 9 numbers evenly spaced over 1.5 to 3.

In [13]:
b1=np.linspace(1.5,3,9)
b1

array([1.5   , 1.6875, 1.875 , 2.0625, 2.25  , 2.4375, 2.625 , 2.8125,
       3.    ])

In [ ]:
#b: Create a 3x3 matrix, b2, which includes random numbers from Gaussian distribution with mean = 1, and sd = 0.75, seed = 1234.

In [14]:
np.random.seed(1234)
b2=np.random.normal(1,0.75,(3,3))
b2

array([[1.35357637, 0.10676823, 2.07453023],
       [0.76551108, 0.45955845, 1.66537221],
       [1.64469131, 0.52260737, 1.01177228]])

In [ ]:
# c: Calculate the determinant of b2.

In [25]:
b2_det=np.linalg.det(b2)
b2_det

-1.0770051050177027

In [ ]:
# d: What is the transpose of matrix b2?

In [15]:
b2.T

array([[1.35357637, 0.76551108, 1.64469131],
       [0.10676823, 0.45955845, 0.52260737],
       [2.07453023, 1.66537221, 1.01177228]])

In [ ]:
# e: Convert b1 into a 3x3 matrix.

In [17]:
b1=b1.reshape(3,3)
b1

array([[1.5   , 1.6875, 1.875 ],
       [2.0625, 2.25  , 2.4375],
       [2.625 , 2.8125, 3.    ]])

In [ ]:
# f: Calculate summation of b1 and b2.

In [18]:
b1+b2

array([[2.85357637, 1.79426823, 3.94953023],
       [2.82801108, 2.70955845, 4.10287221],
       [4.26969131, 3.33510737, 4.01177228]])

In [ ]:
# g: Calculate matrix multiplication of b1 and b2.

In [20]:
np.dot(b1,b2)

array([[ 6.40596071,  1.91554605,  7.81918396],
       [ 8.52308626,  2.52807145, 10.49200098],
       [10.64021182,  3.14059686, 13.16481801]])

In [ ]:
# h: Call all numbers of b2 which are greater than mean of b2.

In [21]:
b2[(b2>b2.mean())]

array([1.35357637, 2.07453023, 1.66537221, 1.64469131])

In [ ]:
#i: Scale matrix b2 using min-max scaling method. End of Code

In [24]:
min=np.min(b2)
max=np.max(b2)
print('min of b1 is:',min)
print('max of  b1 is:',max)

min of b1 is: 0.1067682289701517
max of  b1 is: 2.074530226319573
